### PR TITLE
Chore/GitHub action test

### PR DESCRIPTION
**Pull request by fatjan**
This is to add a runner when a PR is created, the tests should be run

### CODE REVIEW

**Review by anangyoga — COMMENTED** [review]
I think everything is ok.

**Comment by fatjan** [comment]
> I think everything is ok.

Could you please approve it? Thanks

**Review by muhammadiqbalid83 — COMMENTED** [review]
saya belum pernah menggunakan github action

**Comment by fatjan** [comment]
> saya belum pernah menggunakan github action

ok, could you please approve this PR?

Thanks

**Pull request closed without merging**
